FROM apache/airflow:1.10.15

COPY requirements.txt /requirements.txt

RUN set -ex && \
  apt-get install -yqq --no-install-recommends \
  build-essential && \
  python -m pip install --upgrade pip && \
  pip install --no-cache-dir --user -r /requirements.txt
