from airflow.models import Variable


def get_environments():
    return {'ENVIRONMENT': Variable.get('ENVIRONMENT'),
            'BASE_API_DB_PORT':  Variable.get('BASE_API_DB_PORT'),
            'BASE_API_DB_HOST': Variable.get('BASE_API_DB_HOST'),
            'BASE_API_DB_NAME': Variable.get('BASE_API_DB_NAME'),
            'BASE_API_DB_USERNAME': Variable.get('BASE_API_DB_USERNAME'),
            'BASE_API_DB_PASSWORD': Variable.get('BASE_API_DB_PASSWORD'),
            'BASE_API_TOKEN': Variable.get('BASE_API_TOKEN'),
            'ANALYTICS_DB_PORT': Variable.get('ANALYTICS_DB_PORT'),
            'ANALYTICS_DB_HOST': Variable.get('ANALYTICS_DB_HOST'),
            'ANALYTICS_DB_NAME': Variable.get('ANALYTICS_DB_NAME'),
            'ANALYTICS_DB_USERNAME': Variable.get('ANALYTICS_DB_USERNAME'),
            'ANALYTICS_DB_PASSWORD': Variable.get('ANALYTICS_DB_PASSWORD'),
            'AI_MANAGER_DB_HOST': Variable.get('AI_MANAGER_DB_HOST'),
            'AI_MANAGER_DB_PORT': Variable.get('AI_MANAGER_DB_PORT'),
            'AI_MANAGER_DB_USERNAME': Variable.get('AI_MANAGER_DB_USERNAME'),
            'AI_MANAGER_DB_PASSWORD': Variable.get('AI_MANAGER_DB_PASSWORD'),
            'AI_MANAGER_DB_NAME': Variable.get('AI_MANAGER_DB_NAME'),
            'STATS_DB_PORT': Variable.get('STATS_DB_PORT'),
            'STATS_DB_HOST': Variable.get('STATS_DB_HOST'),
            'STATS_DB_NAME': Variable.get('STATS_DB_NAME'),
            'STATS_DB_USERNAME': Variable.get('STATS_DB_USERNAME'),
            'STATS_DB_PASSWORD': Variable.get('STATS_DB_PASSWORD'),
            'AIRFLOW_SMTP_HOST': Variable.get('AIRFLOW_SMTP_HOST'),
            'AIRFLOW_SMTP_USER': Variable.get('AIRFLOW_SMTP_USER'),
            'AIRFLOW_SMTP_PASSWORD': Variable.get('AIRFLOW_SMTP_PASSWORD'),
            'AIRFLOW_SMTP_PORT': Variable.get('AIRFLOW_SMTP_PORT'),
            'AIRFLOW_SMTP_STARTTLS': Variable.get('AIRFLOW_SMTP_STARTTLS'),
            'AIRFLOW_SMTP_SSL': Variable.get('AIRFLOW_SMTP_SSL'),
            'AIRFLOW_SMTP_MAIL_FROM': Variable.get('AIRFLOW_SMTP_MAIL_FROM'),}
